#!/bin/sh

rm -rf ~/.config/nvim 2>/dev/null
mkdir -p ~/.config/nvim 2>/dev/null
ln -sf "$PWD/init.lua" "$HOME/.config/nvim/"
ln -sf "$PWD/lua" "$HOME/.config/nvim/"
ln -sf "$PWD/colors" "$HOME/.config/nvim/"
